import type { Metadata } from "next";
import { Bebas_Neue, Crimson_Pro, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/AllPages/shared/Navbar";
import Footer from "@/components/AllPages/shared/Footer";
import CTASection from "@/components/AllPages/Cta/CTA";
import Script from "next/script";
import { LanguageProvider } from "@/components/LanguegeProvider/LanguegeProvider";
import AosInit from "@/components/AosInit/AosInit";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${inter.variable} ${bebasNeue.variable} antialiased !top-[0px] antialiased overflow-x-hidden `}>
        <div id="google_translate_element" className="google-hide"></div>


        <div id="google_translate_element" className="google-hide"></div>

        {/* <Script id="google-translate-init" strategy="afterInteractive">
          {`
    function googleTranslateElementInit() {
     
      new google.translate.TranslateElement(
        {
          pageLanguage: "en",
          includedLanguages: "en,es"
        },
        "google_translate_element"
      );
    }
  `}
        </Script>
        <Script
          src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        /> */}
        <AosInit />
        <LanguageProvider>
          <Navbar />

          {children}

          <CTASection />
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}

